### ISSUE TITLE
what's ppull

### ISSUE THREAD

**Issue by andykitchen** [Prismatic/eng-practices#6]
In the git guide, you mention ppull, is this a special esoteric tool or just a typo?

**Comment by w01fe** [comment]
it's an internal script that's basically just `git pull` followed by `git submodule update`.

**Comment by andykitchen** [comment]
Ok, it might be worth explaining that in the document, it's probably a useful piece of information even for new prismatic employees.

**Comment by w01fe** [comment]
Good call, updated.  Thanks for the feedback!

**Comment by andykitchen** [comment]
Nice! A team I'm on has found this useful, thanks for making it public.
